;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        easy-kill
        org-delete-char
        org-self-insert-command
        org-yank
        smart-move-beginning-of-line
        sp-backward-delete-char
        sp-delete-char
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        beginning-of-buffer
        helm-M-x
        ))
